const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const INTERNAL_SERVER_ERROR = 500;
const OK = 200;
const CREATED = 201;
const FORBIDDEN = 403;
const CONFLICT = 409;
const UNAUTHORIZED = 401;

module.exports = {
  NOT_FOUND,
  BAD_REQUEST,
  INTERNAL_SERVER_ERROR,
  OK,
  CREATED,
  FORBIDDEN,
  CONFLICT,
  UNAUTHORIZED,
};
